### ISSUE TITLE
Не читает опции из gruntfile.coffe

### ISSUE THREAD

**Issue by exdeniz** [htmlhero/grunt-init-block#3]
```
        initBlock:
            options:
                element: '_'
                modifier: '__'
                preprocessor: true
                longModifier: true
            dev:
                src: ['index.html']
                dest: 'b/'
```

Не одна из опций не подключена.
